### ISSUE TITLE
Proxy error retry

### ISSUE THREAD

**Issue by say1j** [DoctorMcKay/node-steam-session#13]
Hey, sometimes proxy can throw code 'ECONNRESET' on connection and login or other functions crashing.
Is there any way to add support for the number of retries for these errors for steam-session and steamcommunity? It's not really right to add a check to every function since these are repetitions and the code will be huge and unreadable.

Exapmles of thrown errors because of that:

Error: Proxy CONNECT 403 Forbidden
 at ClientRequest.<anonymous> (/root/asd/node_modules/@doctormckay/stdlib/components/http/proxyagent.js:54:14)
 at ClientRequest.emit (events.js:400:28)
 at ClientRequest.emit (domain.js:475:12)
 at Socket.socketOnData (_http_client.js:553:11)
 at Socket.emit (events.js:400:28)
 at Socket.emit (domain.js:475:12)
 at addChunk (internal/streams/readable.js:293:12)
 at readableAddChunk (internal/streams/readable.js:267:9)
 at Socket.Readable.push (internal/streams/readable.js:206:10)
 at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
 
Error: tunneling socket could not be established, statusCode=403
 at ClientRequest.onConnect (/root/asd/node_modules/tunnel-agent/index.js:166:19)
 at Object.onceWrapper (events.js:520:26)
 at ClientRequest.emit (events.js:400:28)
 at ClientRequest.emit (domain.js:475:12)
 at Socket.socketOnData (_http_client.js:553:11)
 at Socket.emit (events.js:400:28)
 at Socket.emit (domain.js:475:12)
 at addChunk (internal/streams/readable.js:293:12)
 at readableAddChunk (internal/streams/readable.js:267:9)
 at Socket.Readable.push (internal/streams/readable.js:206:10)
 at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
code: 'ECONNRESET'
}

**Comment by DoctorMcKay** [comment]
1. Your proxy 403 issues are your proxy's fault. I can put auto-proxy-retries on the to-do list, but I can't guarantee I'll get to it anytime soon. Your proxy's reliability is ultimately your responsibility.
2. Your `jobIdBuffer.readBigInt64BE is not a function` suggests that you're using a Node.js version that isn't supported. 12.22.0 or later is required.

**Comment by DoctorMcKay** [comment]
All I can suggest is that you check your environment. Maybe you're using an old node version somehow randomly.

The only reason you'd get `jobIdBuffer.readBigInt64BE is not a function` is if `jobIdBuffer` is a Buffer, but the `readBigInt64BE` function is missing. If it were undefined somehow, you'd instead get `Cannot read property 'readBigInt64BE' of undefined`.

**Comment by venila** [comment]
My app always crash because of this error

`Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)

Process finished with exit code 1
`

I can't caught it in my app.
