### ISSUE TITLE
Error: Malformed login response

### ISSUE THREAD

**Issue by lovesmurf** [DoctorMcKay/node-steam-session#15]
Woke up today and found that I was getting a lot of error messages when receiving cookies, then the process dies off. Please tell me, should I always catch catch on getWebCookies function? And what is causing this error?

```
3|trades   | Error: Malformed login response
3|trades   |     at LoginSession.getWebCookies (/app/node_modules/steam-session/dist/LoginSession.js:397:19)
3|trades   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
3|trades   |     at async checkExpiredTokens (/app/core/tradeHandlers/bot/login.js:68:25)
3|trades   |     at async handle (/app/core/tradeHandlers/bot/login.js:230:11)
3|trades   | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
3|trades   | Error: Malformed login response
3|trades   |     at LoginSession.getWebCookies (/app/node_modules/steam-session/dist/LoginSession.js:397:19)
3|trades   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
3|trades   |     at async checkExpiredTokens (/app/core/tradeHandlers/bot/login.js:68:25)
3|trades   |     at async handle (/app/core/tradeHandlers/bot/login.js:230:11)
3|trades   | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
3|trades   | Error: Malformed login response
3|trades   |     at LoginSession.getWebCookies (/app/node_modules/steam-session/dist/LoginSession.js:397:19)
3|trades   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
3|trades   |     at async checkExpiredTokens (/app/core/tradeHandlers/bot/login.js:68:25)
3|trades   |     at async handle (/app/core/tradeHandlers/bot/login.js:230:11)
3|trades   | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
3|trades   | Error: Malformed login response
3|trades   |     at LoginSession.getWebCookies (/app/node_modules/steam-session/dist/LoginSession.js:397:19)
3|trades   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
3|trades   |     at async checkExpiredTokens (/app/core/tradeHandlers/bot/login.js:68:25)
3|trades   |     at async handle (/app/core/tradeHandlers/bot/login.js:230:11)
3|trades   | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
3|trades   | Error: Malformed login response
3|trades   |     at LoginSession.getWebCookies (/app/node_modules/steam-session/dist/LoginSession.js:397:19)
3|trades   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
3|trades   |     at async checkExpiredTokens (/app/core/tradeHandlers/bot/login.js:68:25)
3|trades   |     at async handle (/app/core/tradeHandlers/bot/login.js:230:11)
3|trades   | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
3|trades   | Error: Malformed login response
3|trades   |     at LoginSession.getWebCookies (/app/node_modules/steam-session/dist/LoginSession.js:397:19)
3|trades   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
3|trades   |     at async checkExpiredTokens (/app/core/tradeHandlers/bot/login.js:68:25)
3|trades   |     at async handle (/app/core/tradeHandlers/bot/login.js:230:11)
```

**Comment by DoctorMcKay** [comment]
Works fine for me. Was this happening yesterday during Steam's weekly downtime?

You should always catch errors from anything that could throw one, especially network requests. Errors are always possible when networks are involved.

**Comment by DoctorMcKay** [comment]
I can't reproduce this.

```js
try {
	session.refreshToken = 'eyAid...';
	console.log(await session.getWebCookies());
} catch (ex) {
	console.log('getWebCookies() error');
	console.log(ex);
}
```

Output:

```
getWebCookies() error
Error: Malformed login response
    at LoginSession.getWebCookies (path\to\steam-session\src\LoginSession.ts:528:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (path\to\steam-session\dev\test2.ts:23:15)
```

**Comment by DoctorMcKay** [comment]
Now that you've posted your code, I can tell you what's wrong with it.

Throwing an error in an event handler (or rejecting a promise inside an async event handler) does nothing. The error does not get bubbled or caught. You'd need to do this:

```js
          session.on("authenticated", async () => {
            console.log("\nAuthenticated successfully! Printing your tokens now...");
            console.log(`SteamID: ${session.steamID}`);
            console.log(`Account name: ${session.accountName}`);
            console.log(`Access token: ${session.accessToken}`);
            console.log(`Refresh token: ${session.refreshToken}`);

            try {
              logger.info("Take webcookies authenticated");
              const webCookies = await session.getWebCookies();
              logger.info("Taken webcookies success authenticated");
              console.log("Web session cookies:");
              console.log(webCookies);
            } catch (ex) {
              reject(ex);
            }

            community.setCookies(webCookies);

            const decodedAccessToken = jwt.decode(session.accessToken);
            const decodedRefreshToken = jwt.decode(session.refreshToken);
            const accessTokenExpiry = new Date(decodedAccessToken.exp * 1000);
            const refreshTokenExpiry = new Date(decodedRefreshToken.exp * 1000);

            clearTimeout(timeout);
            return resolve();
          });
```
