### ISSUE TITLE
QR code request denial unhandled

### ISSUE THREAD

**Issue by thecrowkeep** [DoctorMcKay/node-steam-session#47]
## Describe the bug
When denying a QR code login request, the denial is not handled or parsed by the error emitter correctly.

## Versions
node-steam-session@1.9.0
node@22.9.0

#### Reproduction:
1. Set up the example [login-with-qr ](https://github.com/DoctorMcKay/node-steam-session/blob/master/examples/login-with-qr.ts)
2. Run the example
3. Scan the QR code
4. When prompted between signing in or canceling, choose cancel
5. => `ERROR: This login attempt has failed! FileNotFound`

#### Stacktrace:
```log
Error: FileNotFound
    at eresultError (steam-session@1.9.0\node_modules\steam-session\dist\helpers.js:14:15)
    at AuthenticationClient.sendRequest (steam-session@1.9.0\node_modules\steam-session\dist\AuthenticationClient.js:243:46)   
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AuthenticationClient.pollLoginStatus (steam-session@1.9.0\node_modules\steam-session\dist\AuthenticationClient.js:147:22)
    at async LoginSession._doPoll (steam-session@1.9.0\node_modules\steam-session\dist\LoginSession.js:493:28) {
  eresult: 9
}
```

**Comment by DoctorMcKay** [comment]
This is expected, just handle the  `error` event.
